import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body className="">{children}</body> 
    </html>
  );
}
